ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'CLIENT_REVIEW_PENDING';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'OPERATOR_REVIEW_PENDING';

ALTER TYPE "TriggerEvent" ADD VALUE IF NOT EXISTS 'CLIENT_OBSERVATION_RECEIVED';
ALTER TYPE "TriggerEvent" ADD VALUE IF NOT EXISTS 'BUDGET_ADJUSTED';
ALTER TYPE "TriggerEvent" ADD VALUE IF NOT EXISTS 'OPERATOR_REVIEW_APPROVED';
ALTER TYPE "TriggerEvent" ADD VALUE IF NOT EXISTS 'ORDER_IN_PRODUCTION';
ALTER TYPE "TriggerEvent" ADD VALUE IF NOT EXISTS 'ORDER_DELAYED';
ALTER TYPE "TriggerEvent" ADD VALUE IF NOT EXISTS 'ORDER_DELIVERED';

ALTER TABLE "orders"
ADD COLUMN "final_price" DECIMAL(10, 2),
ADD COLUMN "client_review_notes" TEXT,
ADD COLUMN "client_reviewed_at" TIMESTAMP(3),
ADD COLUMN "operator_reviewed_at" TIMESTAMP(3),
ADD COLUMN "operator_price_adjustment_reason" TEXT,
ADD COLUMN "production_time_estimate" TEXT,
ADD COLUMN "production_started_at" TIMESTAMP(3),
ADD COLUMN "production_ready_at" TIMESTAMP(3);
